-- =================================================================
-- MOVA DATABASE SCHEMA
-- Paste this entire file into Supabase SQL Editor and run once.
-- =================================================================


-- =================================================================
-- EXTENSIONS
-- =================================================================

create extension if not exists vector;


-- =================================================================
-- LOOKUP TABLES (create first, everything references these)
-- =================================================================

-- Model roles — single source of truth for all 9 models
-- Replaces scattered model_role text fields and system_config RPM rows
create table public.model_roles (
  role text primary key,
  model_name text not null,
  rpm_limit int not null default 0,
  -- 0 = batch only (Arbiter), not subject to real-time rate limiting
  description text,
  is_batch_only boolean default false,
  is_active boolean default true,
  created_at timestamptz default now()
);

insert into public.model_roles (role, model_name, rpm_limit, description, is_batch_only) values
  ('scout',     'meta/llama-3.2-3b-instruct',                       3,  'Conversational elicitation agent',            false),
  ('orion',     'nvidia/nemotron-3-ultra-550b-a55b',                 10, 'Primary reasoning, planning and review',      false),
  ('forge',     'nvidia/llama-3.3-nemotron-super-49b-v1.5',         8,  'Code generation and fixing',                  false),
  ('narrator',  'nvidia/llama-3.3-nemotron-super-49b-v1.5',         3,  'Script writing for voiceover',                false),
  ('guardian',  'nvidia/llama-3.1-nemotron-safety-guard-8b-v3',     2,  'Safety checks on inputs and outputs',         false),
  ('reranker',  'nvidia/rerank-qa-mistral-4b',                      2,  'Reranks RAG candidates by relevance',         false),
  ('lens_text', 'nvidia/nv-embed-v1',                               1,  'Embeddings for natural language content',     false),
  ('lens_code', 'nvidia/nv-embedcode-7b-v1',                        1,  'Embeddings for code content',                 false),
  ('arbiter',   'mistralai/mistral-large-3-675b-instruct-2512',     0,  'Batch quality scoring and promotion',         true);


-- =================================================================
-- SESSIONS TABLE
-- Single source of truth for session_id used across all tables.
-- Previously session_id was a loose text field with no enforcement.
-- =================================================================

create table public.sessions (
  id text primary key,
  -- deterministic session ID generated by the API on project start
  user_id uuid,
  -- nullable: session can start before auth completes
  project_id uuid,
  -- nullable: set once project row is created
  started_at timestamptz default now(),
  last_active_at timestamptz default now(),
  ended_at timestamptz,
  metadata jsonb default '{}'
  -- stores: user_agent, ip_address hash, elicitation_start_time
);


-- =================================================================
-- USERS & PROJECTS
-- =================================================================

create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text not null,
  display_name text,
  avatar_url text,
  subscription_tier text default 'free',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Add FK from sessions to profiles after profiles exists
alter table public.sessions
  add constraint sessions_user_id_fkey
  foreign key (user_id) references public.profiles(id) on delete set null;

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  status text default 'draft',
  -- status: draft | eliciting | planning | generating | rendering | completed | failed
  total_scenes int default 0,
  completed_scenes int default 0,
  final_video_url text,
  final_video_duration_seconds float,
  has_voiceover boolean default false,
  has_background_music boolean default false,
  voiceover_status text default 'none',
  audio_mix_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Add FK from sessions to projects after projects exists
alter table public.sessions
  add constraint sessions_project_id_fkey
  foreign key (project_id) references public.projects(id) on delete set null;


-- =================================================================
-- ELICITATION & PROMPTS
-- =================================================================

create table public.prompt_versions (
  id uuid primary key default gen_random_uuid(),
  model_role text references public.model_roles(role) not null,
  version text not null,
  content text not null,
  is_active boolean default false,
  created_at timestamptz default now(),
  constraint unique_model_version unique(model_role, version)
);

create table public.prompt_history (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  session_id text references public.sessions(id) on delete set null,
  raw_prompt text not null,
  enriched_prompt text,
  elicitation_turns jsonb default '[]',
  requirements jsonb,
  created_at timestamptz default now()
);


-- =================================================================
-- SCENE PLAN & CHECKPOINTS
-- =================================================================

create table public.scenes (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade not null,
  scene_index int not null,
  title text not null,
  visual_description text,
  expected_animation_types text[],
  approximate_duration_seconds float,
  transition_type text,
  dependency_scene_indexes int[] default '{}',
  complexity text default 'medium',
  complexity_score float default 0.5,
  status text default 'pending',
  is_dirty boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(project_id, scene_index)
);

create table public.scene_checkpoints (
  id uuid primary key default gen_random_uuid(),
  scene_id uuid references public.scenes(id) on delete cascade not null,
  project_id uuid references public.projects(id) on delete cascade not null,
  -- project_id kept here intentionally: Celery workers query by
  -- project_id + scene_index directly without always having scene_id
  scene_index int not null,
  attempt_number int default 1,
  celery_task_id text unique,
  retrieved_context jsonb,
  generated_code text,
  review_issues jsonb,
  fix_attempts int default 0,
  final_code text,
  ast_parse_passed boolean,
  dry_run_passed boolean,
  dry_run_error text,
  dry_run_attempts int default 0,
  render_status text default 'pending',
  clip_url text,
  render_duration_seconds float,
  render_error text,
  extracted_color_palette jsonb,
  extracted_coordinate_systems jsonb,
  extracted_manim_objects jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(project_id, scene_index, attempt_number)
);


-- =================================================================
-- NARRATOR & AUDIO
-- =================================================================

create table public.narrator_scripts (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade not null,
  full_script text not null,
  segments jsonb not null,
  voice_id text,
  voiceover_tone text,
  status text default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint segments_is_array check (jsonb_typeof(segments) = 'array')
);

create table public.audio_files (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade not null,
  scene_id uuid references public.scenes(id) on delete set null,
  audio_type text not null,
  file_url text not null,
  duration_seconds float,
  volume_level float default 1.0,
  is_temporary boolean default false,
  created_at timestamptz default now()
);

create table public.music_library (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  artist text,
  mood text not null,
  energy_level text not null,
  duration_seconds float not null,
  file_url text not null,
  license text not null default 'royalty_free_cc0',
  is_active boolean default true,
  created_at timestamptz default now()
);


-- =================================================================
-- AGENT RUNS & OBSERVABILITY
-- =================================================================

create table public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade not null,
  scene_id uuid references public.scenes(id) on delete set null,
  session_id text references public.sessions(id) on delete set null,
  model_role text references public.model_roles(role) not null,
  agent_name text not null,
  langsmith_trace_id text,
  input_tokens int,
  output_tokens int,
  latency_ms int,
  status text default 'running',
  error_message text,
  attempt_number int default 1,
  created_at timestamptz default now(),
  completed_at timestamptz
);

create table public.feedback_events (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade not null,
  scene_id uuid references public.scenes(id) on delete set null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  session_id text references public.sessions(id) on delete set null,
  retrieval_log_id uuid,
  affected_document_ids uuid[] default '{}',
  event_type text not null,
  metadata jsonb,
  created_at timestamptz default now()
);


-- =================================================================
-- PROJECT MEMORY
-- =================================================================

create table public.project_memory (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  preferred_visual_style text,
  preferred_voice_id text,
  animation_complexity_preference text,
  color_palettes jsonb default '[]',
  successful_animation_types text[] default '{}',
  updated_at timestamptz default now(),
  unique(user_id)
);


-- =================================================================
-- RAG DOCUMENTS
-- =================================================================

create table public.rag_documents (
  id uuid primary key default gen_random_uuid(),
  content text not null,
  content_type text not null,
  source_type text not null,
  animation_category text,
  manim_version text,
  is_candidate boolean default false,
  is_stale boolean default false,
  quality_score float default 0.5,
  retrieval_count int default 0,
  retrieval_success_rate float default 0.0,
  embedding vector(1536),
  embedding_model text,
  tags text[] default '{}',
  metadata jsonb default '{}',
  ttl_expires_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- =================================================================
-- RAG RETRIEVAL LOGS
-- =================================================================

create table public.rag_retrieval_logs (
  id uuid primary key default gen_random_uuid(),
  session_id text references public.sessions(id) on delete set null,
  project_id uuid references public.projects(id) on delete cascade,
  scene_id uuid references public.scenes(id) on delete set null,
  query_text text not null,
  query_embedding vector(1536),
  retrieved_document_ids uuid[] default '{}',
  similarity_scores float[] default '{}',
  reranked_document_ids uuid[] default '{}',
  cache_hit boolean default false,
  retrieval_latency_ms int,
  created_at timestamptz default now()
);

-- FK on feedback_events now that rag_retrieval_logs exists
alter table public.feedback_events
  add constraint feedback_retrieval_log_fkey
  foreign key (retrieval_log_id) references public.rag_retrieval_logs(id)
  on delete set null;


-- =================================================================
-- PAGEINDEX METADATA
-- =================================================================

create table public.pageindex_indexes (
  id uuid primary key default gen_random_uuid(),
  manim_version text not null unique,
  storage_path text not null,
  node_count int,
  build_status text default 'pending',
  built_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- =================================================================
-- API CHANGES
-- =================================================================

create table public.api_changes (
  id uuid primary key default gen_random_uuid(),
  manim_version text not null,
  change_description text,
  affected_apis text[] default '{}',
  released_at timestamptz,
  created_at timestamptz default now()
);


-- =================================================================
-- RATE LIMIT EVENTS
-- =================================================================

create table public.rate_limit_events (
  id uuid primary key default gen_random_uuid(),
  session_id text references public.sessions(id) on delete set null,
  project_id uuid references public.projects(id) on delete cascade,
  model_role text references public.model_roles(role) not null,
  event_type text not null,
  queue_position int,
  wait_time_ms int,
  created_at timestamptz default now()
);


-- =================================================================
-- ADMIN SYSTEM
-- =================================================================

create table public.admin_users (
  id uuid references auth.users(id) on delete cascade primary key,
  email text not null,
  role text not null default 'admin',
  -- role: viewer | admin | super_admin
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid references public.admin_users(id) on delete set null,
  action text not null,
  target_table text,
  target_id uuid,
  before_state jsonb,
  after_state jsonb,
  ip_address text,
  created_at timestamptz default now()
);


-- =================================================================
-- DOCUMENT MANAGEMENT
-- =================================================================

create table public.document_ingestion_jobs (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid references public.admin_users(id) on delete set null,
  job_type text not null,
  status text default 'pending',
  source_url text,
  source_type text,
  manim_version text,
  total_documents int default 0,
  processed_documents int default 0,
  failed_documents int default 0,
  skipped_duplicates int default 0,
  error_log jsonb default '[]',
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create table public.document_review_queue (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.rag_documents(id) on delete cascade not null,
  ingestion_job_id uuid references public.document_ingestion_jobs(id) on delete set null,
  review_status text default 'pending',
  reviewed_by uuid references public.admin_users(id) on delete set null,
  review_notes text,
  arbiter_score float,
  arbiter_reasoning text,
  reviewed_at timestamptz,
  created_at timestamptz default now()
);


-- =================================================================
-- PIPELINE PERFORMANCE
-- =================================================================

create table public.pipeline_performance_snapshots (
  id uuid primary key default gen_random_uuid(),
  snapshot_date date not null unique,
  total_projects_created int default 0,
  total_scenes_generated int default 0,
  first_pass_render_success_rate float,
  average_fix_attempts_per_scene float,
  average_scene_generation_latency_ms int,
  average_full_pipeline_latency_ms int,
  model_call_counts jsonb default '{}',
  model_token_usage jsonb default '{}',
  model_error_rates jsonb default '{}',
  retrieval_cache_hit_rate float,
  average_retrieval_latency_ms int,
  retrieval_mrr float,
  top_animation_categories jsonb default '[]',
  rate_limit_hit_count int default 0,
  average_queue_wait_ms int,
  peak_queue_depth int,
  total_videos_completed int default 0,
  total_videos_failed int default 0,
  average_video_duration_seconds float,
  created_at timestamptz default now()
);

create table public.model_daily_stats (
  id uuid primary key default gen_random_uuid(),
  stat_date date not null,
  model_role text references public.model_roles(role) not null,
  total_calls int default 0,
  successful_calls int default 0,
  failed_calls int default 0,
  retried_calls int default 0,
  total_input_tokens int default 0,
  total_output_tokens int default 0,
  average_latency_ms int,
  p95_latency_ms int,
  p99_latency_ms int,
  rate_limit_hits int default 0,
  created_at timestamptz default now(),
  unique(stat_date, model_role)
);

create table public.rag_document_stats (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.rag_documents(id) on delete cascade not null,
  stat_date date not null,
  retrieval_count int default 0,
  used_in_generation_count int default 0,
  positive_feedback_count int default 0,
  negative_feedback_count int default 0,
  render_success_when_used int default 0,
  render_fail_when_used int default 0,
  created_at timestamptz default now(),
  unique(document_id, stat_date)
);


-- =================================================================
-- SYSTEM LOGS
-- =================================================================

create table public.system_logs (
  id uuid primary key default gen_random_uuid(),
  log_level text not null,
  service text not null,
  event_type text not null,
  message text not null,
  project_id uuid references public.projects(id) on delete set null,
  scene_id uuid references public.scenes(id) on delete set null,
  session_id text references public.sessions(id) on delete set null,
  celery_task_id text,
  correlation_id text,
  metadata jsonb default '{}',
  stack_trace text,
  created_at timestamptz default now()
);

create table public.dead_letter_queue (
  id uuid primary key default gen_random_uuid(),
  celery_task_id text not null,
  task_name text not null,
  queue_name text not null,
  project_id uuid references public.projects(id) on delete set null,
  scene_id uuid references public.scenes(id) on delete set null,
  attempt_count int not null,
  last_error text,
  last_traceback text,
  task_args jsonb,
  task_kwargs jsonb,
  first_failed_at timestamptz not null,
  last_failed_at timestamptz not null,
  resolved boolean default false,
  resolved_by uuid references public.admin_users(id) on delete set null,
  resolved_at timestamptz,
  resolution_notes text,
  created_at timestamptz default now()
);


-- =================================================================
-- SYSTEM CONFIG
-- RPM limits live in model_roles now.
-- Only non-model runtime config lives here.
-- =================================================================

create table public.system_config (
  key text primary key,
  value jsonb not null,
  description text,
  updated_by uuid references public.admin_users(id) on delete set null,
  updated_at timestamptz default now()
);

insert into public.system_config (key, value, description) values
  ('rag_candidate_quality_threshold',  '0.65',  'Minimum quality score for Arbiter weekly promotion'),
  ('rag_candidate_min_retrievals',     '5',     'Minimum retrieval events before candidate is eligible'),
  ('rag_semantic_cache_threshold',     '0.95',  'Cosine similarity threshold for semantic cache hits'),
  ('rag_duplicate_threshold',          '0.92',  'Cosine similarity threshold for near-duplicate detection'),
  ('max_fix_iterations',               '3',     'Maximum Forge fix attempts per scene before best-effort return'),
  ('manim_dry_run_timeout_seconds',    '30',    'Hard timeout for Manim dry-run sandboxed subprocess'),
  ('elevenlabs_concurrency',           '1',     'Max concurrent ElevenLabs TTS requests (free tier limit)'),
  ('music_duck_under_voiceover',       '0.30',  'Background music volume under voiceover segments'),
  ('music_duck_in_gaps',               '0.60',  'Background music volume in silent gaps'),
  ('maintenance_mode',                 'false', 'Puts entire system in read-only maintenance mode');


-- =================================================================
-- INDEXES
-- =================================================================

create index idx_sessions_user_id on public.sessions(user_id);
create index idx_sessions_project_id on public.sessions(project_id);
create index idx_sessions_started_at on public.sessions(started_at);
create index idx_profiles_email on public.profiles(email);
create index idx_projects_user_id on public.projects(user_id);
create index idx_projects_status on public.projects(status);
create index idx_prompt_versions_model_role on public.prompt_versions(model_role, is_active);
create index idx_prompt_history_project_id on public.prompt_history(project_id);
create index idx_prompt_history_user_id on public.prompt_history(user_id);
create index idx_prompt_history_session_id on public.prompt_history(session_id);
create index idx_scenes_project_id on public.scenes(project_id);
create index idx_scenes_project_scene on public.scenes(project_id, scene_index);
create index idx_scenes_status on public.scenes(status);
create index idx_scene_checkpoints_scene_id on public.scene_checkpoints(scene_id);
create index idx_scene_checkpoints_project_scene on public.scene_checkpoints(project_id, scene_index, attempt_number);
create index idx_scene_checkpoints_celery_task on public.scene_checkpoints(celery_task_id);
create index idx_narrator_scripts_project_id on public.narrator_scripts(project_id);
create index idx_audio_files_project_id on public.audio_files(project_id);
create index idx_audio_files_scene_id on public.audio_files(scene_id);
create index idx_music_library_mood on public.music_library(mood, energy_level);
create index idx_agent_runs_project_id on public.agent_runs(project_id);
create index idx_agent_runs_model_role on public.agent_runs(model_role);
create index idx_agent_runs_langsmith on public.agent_runs(langsmith_trace_id);
create index idx_agent_runs_session_id on public.agent_runs(session_id);
create index idx_feedback_events_project_id on public.feedback_events(project_id);
create index idx_feedback_events_user_id on public.feedback_events(user_id);
create index idx_feedback_events_session_id on public.feedback_events(session_id);
create index idx_project_memory_user_id on public.project_memory(user_id);
create index idx_rag_embedding on public.rag_documents
  using hnsw (embedding vector_cosine_ops) with (m = 16, ef_construction = 64);
create index idx_rag_version_candidate_stale on public.rag_documents
  using btree (manim_version, is_candidate, is_stale);
create index idx_rag_animation_category on public.rag_documents(animation_category);
create index idx_rag_source_type on public.rag_documents(source_type);
create index idx_rag_metadata on public.rag_documents using gin (metadata);
create index idx_rag_tags on public.rag_documents using gin (tags);
create index idx_rag_ttl on public.rag_documents(ttl_expires_at)
  where ttl_expires_at is not null;
create index idx_rag_retrieval_logs_project_id on public.rag_retrieval_logs(project_id);
create index idx_rag_retrieval_logs_session_id on public.rag_retrieval_logs(session_id);
create index idx_rag_retrieval_logs_created_at on public.rag_retrieval_logs(created_at);
create index idx_pageindex_version on public.pageindex_indexes(manim_version);
create index idx_rate_limit_events_session on public.rate_limit_events(session_id);
create index idx_rate_limit_events_model_role on public.rate_limit_events(model_role, created_at);
create index idx_admin_audit_logs_admin_id on public.admin_audit_logs(admin_id);
create index idx_admin_audit_logs_created_at on public.admin_audit_logs(created_at);
create index idx_admin_audit_logs_target on public.admin_audit_logs(target_table, target_id);
create index idx_ingestion_jobs_status on public.document_ingestion_jobs(status);
create index idx_ingestion_jobs_created_at on public.document_ingestion_jobs(created_at);
create index idx_review_queue_document_id on public.document_review_queue(document_id);
create index idx_review_queue_status on public.document_review_queue(review_status);
create index idx_pipeline_snapshots_date on public.pipeline_performance_snapshots(snapshot_date);
create index idx_model_daily_stats_date on public.model_daily_stats(stat_date);
create index idx_model_daily_stats_role on public.model_daily_stats(model_role, stat_date);
create index idx_rag_doc_stats_document on public.rag_document_stats(document_id);
create index idx_rag_doc_stats_date on public.rag_document_stats(stat_date);
create index idx_system_logs_level on public.system_logs(log_level, created_at);
create index idx_system_logs_service on public.system_logs(service, created_at);
create index idx_system_logs_project_id on public.system_logs(project_id);
create index idx_system_logs_correlation on public.system_logs(correlation_id);
create index idx_system_logs_session_id on public.system_logs(session_id);
create index idx_system_logs_created_at on public.system_logs(created_at);
create index idx_dlq_project_id on public.dead_letter_queue(project_id);
create index idx_dlq_resolved on public.dead_letter_queue(resolved, created_at);
create index idx_dlq_task_name on public.dead_letter_queue(task_name);


-- =================================================================
-- ROW LEVEL SECURITY
-- =================================================================

alter table public.model_roles enable row level security;
alter table public.sessions enable row level security;
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.prompt_versions enable row level security;
alter table public.prompt_history enable row level security;
alter table public.scenes enable row level security;
alter table public.scene_checkpoints enable row level security;
alter table public.narrator_scripts enable row level security;
alter table public.audio_files enable row level security;
alter table public.music_library enable row level security;
alter table public.agent_runs enable row level security;
alter table public.feedback_events enable row level security;
alter table public.project_memory enable row level security;
alter table public.rag_documents enable row level security;
alter table public.rag_retrieval_logs enable row level security;
alter table public.pageindex_indexes enable row level security;
alter table public.api_changes enable row level security;
alter table public.rate_limit_events enable row level security;
alter table public.admin_users enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.document_ingestion_jobs enable row level security;
alter table public.document_review_queue enable row level security;
alter table public.pipeline_performance_snapshots enable row level security;
alter table public.model_daily_stats enable row level security;
alter table public.rag_document_stats enable row level security;
alter table public.system_logs enable row level security;
alter table public.dead_letter_queue enable row level security;
alter table public.system_config enable row level security;


-- Helper: check if the calling user is an active admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.admin_users
    where id = auth.uid() and is_active = true
  );
end;
$$ language plpgsql security definer;


-- model_roles: all authenticated users can read
create policy "authenticated read model roles"
  on public.model_roles for select
  using (auth.role() = 'authenticated');

-- sessions
create policy "users manage own sessions"
  on public.sessions for all
  using (auth.uid() = user_id);

-- profiles
create policy "users manage own profile"
  on public.profiles for all
  using (auth.uid() = id);

-- projects
create policy "users manage own projects"
  on public.projects for all
  using (auth.uid() = user_id);

-- prompt versions
create policy "authenticated read prompt versions"
  on public.prompt_versions for select
  using (auth.role() = 'authenticated');

-- prompt history
create policy "users see own prompt history"
  on public.prompt_history for all
  using (auth.uid() = user_id);

-- scenes
create policy "users see own scenes"
  on public.scenes for all
  using (
    project_id in (select id from public.projects where user_id = auth.uid())
  );

-- scene checkpoints
create policy "users see own checkpoints"
  on public.scene_checkpoints for all
  using (
    project_id in (select id from public.projects where user_id = auth.uid())
  );

-- narrator scripts
create policy "users see own narrator scripts"
  on public.narrator_scripts for all
  using (
    project_id in (select id from public.projects where user_id = auth.uid())
  );

-- audio files
create policy "users see own audio files"
  on public.audio_files for all
  using (
    project_id in (select id from public.projects where user_id = auth.uid())
  );

-- music library
create policy "authenticated read music library"
  on public.music_library for select
  using (auth.role() = 'authenticated' and is_active = true);

-- agent runs
create policy "users see own agent runs"
  on public.agent_runs for all
  using (
    project_id in (select id from public.projects where user_id = auth.uid())
  );

-- feedback events
create policy "users see own feedback"
  on public.feedback_events for all
  using (auth.uid() = user_id);

-- project memory
create policy "users see own memory"
  on public.project_memory for all
  using (auth.uid() = user_id);

-- rag documents
create policy "authenticated read rag"
  on public.rag_documents for select
  using (auth.role() = 'authenticated');
create policy "service role manages rag"
  on public.rag_documents for all
  using (auth.role() = 'service_role');

-- rag retrieval logs
create policy "users see own retrieval logs"
  on public.rag_retrieval_logs for select
  using (
    project_id in (select id from public.projects where user_id = auth.uid())
  );

-- pageindex
create policy "authenticated read pageindex"
  on public.pageindex_indexes for select
  using (auth.role() = 'authenticated');

-- api changes
create policy "authenticated read api changes"
  on public.api_changes for select
  using (auth.role() = 'authenticated');

-- rate limit events
create policy "users see own rate limit events"
  on public.rate_limit_events for select
  using (
    project_id in (select id from public.projects where user_id = auth.uid())
  );

-- all admin tables
create policy "admins only" on public.admin_users
  for all using (public.is_admin());
create policy "admins only" on public.admin_audit_logs
  for all using (public.is_admin());
create policy "admins only" on public.document_ingestion_jobs
  for all using (public.is_admin());
create policy "admins only" on public.document_review_queue
  for all using (public.is_admin());
create policy "admins only" on public.pipeline_performance_snapshots
  for all using (public.is_admin());
create policy "admins only" on public.model_daily_stats
  for all using (public.is_admin());
create policy "admins only" on public.rag_document_stats
  for all using (public.is_admin());
create policy "admins only" on public.system_logs
  for all using (public.is_admin());
create policy "admins only" on public.dead_letter_queue
  for all using (public.is_admin());
create policy "admins only" on public.system_config
  for all using (public.is_admin());


-- =================================================================
-- TRIGGERS
-- =================================================================

create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger handle_updated_at before update on public.profiles
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.projects
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.scenes
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.scene_checkpoints
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.narrator_scripts
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.rag_documents
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.pageindex_indexes
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.admin_users
  for each row execute function public.handle_updated_at();
create trigger handle_updated_at before update on public.system_config
  for each row execute function public.handle_updated_at();

-- Auto-create profile and memory row on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);

  insert into public.project_memory (user_id)
  values (new.id);

  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- =================================================================
-- MAKE YOURSELF SUPER ADMIN
-- After running this entire file, run this separately with your
-- real Supabase auth user UUID:
--
-- insert into public.admin_users (id, email, role)
-- values ('<your-auth-user-uuid>', '<your-email>', 'super_admin');
-- =================================================================